# Source: cluster-api-byoh/templates/byoh-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  name: f7640707-control-plane
  namespace: f7640707
spec:
  template:
    spec:
      selector:
        matchLabels:
          role: control-plane
